//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VkApiParser.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VkApiParser.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[contains(@class, &apos;dev_page_block&apos;)]/div[contains(@class, &apos;dev_methods_sect_rows&apos;)].
        /// </summary>
        internal static string API_GROUPS {
            get {
                return ResourceManager.GetString("API_GROUPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div[contains(@class, &apos;dev_method_desc&apos;)].
        /// </summary>
        internal static string API_METHOD_DESC {
            get {
                return ResourceManager.GetString("API_METHOD_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div[contains(@class, &apos;dev_sett_block&apos;)].
        /// </summary>
        internal static string API_METHOD_DETAILS {
            get {
                return ResourceManager.GetString("API_METHOD_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[contains(@class, &apos;dev_method_page&apos;)].
        /// </summary>
        internal static string API_METHOD_PAGE {
            get {
                return ResourceManager.GetString("API_METHOD_PAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //table[contains(@class, &apos;dev_params_table&apos;)]/tr[contains(@class, &apos;dev_param_row&apos;)].
        /// </summary>
        internal static string API_METHOD_PARAMS {
            get {
                return ResourceManager.GetString("API_METHOD_PARAMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div[contains(@class, &apos;dev_method_res&apos;)].
        /// </summary>
        internal static string API_METHOD_RESULT {
            get {
                return ResourceManager.GetString("API_METHOD_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[contains(@id,&apos;dev_page_cont&apos;)]/div/div[contains(@class, &apos;dev_version&apos;)].
        /// </summary>
        internal static string API_VERSIONS_SELECTOR {
            get {
                return ResourceManager.GetString("API_VERSIONS_SELECTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://vk.com/dev/.
        /// </summary>
        internal static string BASE_DEV_URL {
            get {
                return ResourceManager.GetString("BASE_DEV_URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a[contains(@class, &apos;dev_methods_list_row&apos;)].
        /// </summary>
        internal static string GROUP_METHODS {
            get {
                return ResourceManager.GetString("GROUP_METHODS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div[contains(@class, &apos;wk_sub_header&apos;)].
        /// </summary>
        internal static string METHOD_GROUP_TITLE {
            get {
                return ResourceManager.GetString("METHOD_GROUP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to div[contains(@class, &apos;dev_methods_list_name&apos;)]/span[contains(@class, &apos;dev_methods_list_span&apos;)].
        /// </summary>
        internal static string METHOD_TITLE {
            get {
                return ResourceManager.GetString("METHOD_TITLE", resourceCulture);
            }
        }
    }
}
